name: build-catalog
on:
  push:
    paths: ["*.pdf"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pandas PyPDF2
      - run: python build_catalog.py
      - name: Commit updated catalog
        run: |
          git config user.name catalog-bot
          git config user.email bot@example.com
          git add catalog
          git diff --cached --quiet || git commit -m "auto: update catalog"
      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
